return {
	require("carlos.plugins.telescope")[1],
	require("carlos.plugins.telescope")[2],
	require("carlos.plugins.treesitter"),
	require("carlos.themes.catppuccin"),
	require("carlos.plugins.neotree"),
	require("carlos.plugins.lspconfig"),
	require("carlos.plugins.lspsignature"),
	require("carlos.plugins.cmp"),
	require("carlos.plugins.neodev"),
	require("carlos.plugins.whichkey"),
	require("carlos.plugins.alpha"),
	require("carlos.plugins.toggleterm"),
	require("carlos.plugins.nvim-snippets")[1],
	require("carlos.plugins.nvim-snippets")[2],
}
