vim9script
filetype plugin indent on
syntax on
set background=dark
colorscheme wildcharm
set backupdir=~/.cache/vim/backup/
set directory=~/.cache/vim/swap/
set undodir=~/.cache/vim/undo/
set encoding=UTF-8
set fileencodings=utf-8,default
set nowrap
set shiftwidth=2
set tabstop=2
set textwidth=78
set backspace=indent,eol,start
set numberwidth=4
set relativenumber
set incsearch 
set ruler
set showcmd
set viminfo='20,\"50
set helplang=en,de
set autoread
set timeout
set ttimeout
set ttimeoutlen=100
set wildmenu
g:wildoptions = "pum"
g:mapleader = " "
g:maplocalleader = ","
#g:lsp_log_file = expand('~/.vim/vim-lsp.log')

if empty(glob('~/.vim/autoload/plug.vim'))
  silent execute '!curl -fLo ~/.vim/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin('~/.vim/vim-plug')
Plug 'preservim/nerdtree'
Plug 'ryanoasis/vim-devicons'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-endwise'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'preservim/nerdcommenter'
call plug#end()

nnoremap <Leader>b <Cmd>Buffers<CR>
nnoremap <Leader>c <Cmd>edit $MYVIMRC<CR>
nnoremap <Leader>e <Cmd>NERDTreeToggle<CR>
nnoremap <Leader>f <Cmd>Files<CR>
nnoremap <Leader>r <Cmd>source $MYVIMRC<CR>
nnoremap <Leader>s <Cmd>Rg<CR>
noremap \ :term ++kill="kill"<CR>
tnoremap \ <CR><C-D>

var c_lspinfo = {
	'name': 'clangd',
	'cmd': ['clangd', '--background-index'],
	'allowlist': ['c'],
	'blocklist': [],
	'config': {},
	'workspace_config': {}
}
var lua_lspinfo = {
	'name': 'lua-language-server',
	'cmd': ['lua-language-server', '--stdio'],
	'allowlist': ['lua'],
	'blocklist': [],
	'config': {},
	'workspace_config': {}
}
var python_lspinfo = {
	'name': 'pylsp',
	'cmd': ['pylsp'],
	'allowlist': ['python'],
	'blocklist': [],
	'config': {},
	'workspace_config': {}
}
var rust_lsp_info = {
	'name': 'rust-analyzer',
	'cmd': ['rust-analyzer', '--log-file', './rust.log'],
	'allowlist': ['rust'],
	'blocklist': [],
	'config': {},
	'workspace_config': {}
}
var vim_lsp_info = {
	'name': 'vim-language-server',
	'cmd': ['vim-language-server', '--stdio'],
	'allowlist': ['vim'],
	'initialization_options': {
		'vimruntime': $VIMRUNTIME,
		'runtimepath': &rtp
	},
	'blocklist': [],
	'config': {},
	'workspace_config': {}
}

if executable('clangd')
	au User lsp_setup lsp#register_server(c_lspinfo)
endif
if executable('lua-language-server')
	au User lsp_setup lsp#register_server(lua_lspinfo)
endif
if executable('pylsp')
	au User lsp_setup lsp#register_server(python_lspinfo)
endif
if executable('rust-analyzer')
	au User lsp_setup lsp#register_server(rust_lsp_info)
endif
if executable('vim-language-server')
	au User lsp_setup lsp#register_server(vim_lsp_info)
endif

def On_lsp_buffer_enabled(): void
	setlocal omnifunc=lsp#complete
	if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif

	# peek- infixable
	nnoremap <buffer> <leader>d <plug>(lsp-definition)
	nnoremap <buffer> <leader>g <plug>(lsp-type-definition)
  nnoremap <buffer> <leader>v <plug>(lsp-implementation)
  nnoremap <buffer> <leader>w <plug>(lsp-type-hierarchy)
  nnoremap <buffer> <leader>z <plug>(lsp-declaration)

	# -float or -preview appendable
  nnoremap <buffer> <leader>i <plug>(lsp-code-action)
  nnoremap <buffer> <leader>t <plug>(lsp-hover)

	# -nowrap removable
  nnoremap <buffer> <leader>m <plug>(lsp-next-diagnostic-nowrap)

	# nothing
  nnoremap <buffer> <leader>j <plug>(lsp-code-lens)
  nnoremap <buffer> <leader>k <plug>(lsp-document-symbol)
  nnoremap <buffer> <leader>l <plug>(lsp-document-diagnostics)
  nnoremap <buffer> <leader>n <plug>(lsp-next-error-nowrap)
  nnoremap <buffer> <leader>o <plug>(lsp-next-warning-nowrap)
  nnoremap <buffer> <leader>p <plug>(lsp-preview-close)
  nnoremap <buffer> <leader>q <plug>(lsp-preview-focus)
  nnoremap <buffer> <leader>r <plug>(lsp-references)
  nnoremap <buffer> <leader>u <plug>(lsp-rename)
  nnoremap <buffer> <leader>y <plug>(lsp-status)

	g:lsp_format_sync_timeout = 1000
	autocmd! BufWritePre *.rs execute('LspDocumentFormatSync')
enddef

augroup lsp_install
	au!
	autocmd User lsp_buffer_enabled call On_lsp_buffer_enabled()
augroup END

# vim: set ft=vim :
