#!/usr/bin/sh

while xsetroot -name "date: `date` | uptime: `uptime | sed 's/.*,//'` | battery: `cat /sys/class/power_supply/BAT0/capacity` | memory: `free -h | awk '(NR==2){ print $3 }'`/`free -h | awk '(NR==2){ print $2 }'` | enp3s0: `cat /sys/class/net/enp3s0/operstate`, wlan0: `cat /sys/class/net/wlan0/operstate`"
do
	sleep 60
done &

exec dwm
