#!/usr/bin/sh

~/.fehbg &

while xsetroot -name "date: `date | sed 's/\(.*\) -03 2024/\1/'` | uptime: `uptime | sed 's/\s*[0-9]*:[0-9]*:[0-9]*[^0-9]*\([0-9]*\)\s*\([a-z]*\),.*/\1 \2/'` | battery: `cat /sys/class/power_supply/BAT0/capacity` | memory: `free -h | awk '(NR==2){ print $3 }'`/`free -h | awk '(NR==2){ print $2 }'` | enp3s0: `cat /sys/class/net/enp3s0/operstate`, wlan0: `cat /sys/class/net/wlan0/operstate`"
do
	sleep 120
done &

exec dwm
