# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

# Put your fun stuff here.

export EDITOR="vim"

export NVM_DIR="$HOME/.config/nvm"

# This loads nvm
if test -s "$NVM_DIR/nvm.sh"; then
	\. "$NVM_DIR/nvm.sh"
fi

# This loads nvm bash_completion
if test -s "$NVM_DIR/bash_completion"; then
	\. "$NVM_DIR/bash_completion"
fi

if test -z "${XDG_RUNTIME_DIR}"; then
	export XDG_RUNTIME_DIR="/run/user/$(id -u)"
fi

alias ls="ls --color --group-directories-first --sort=extension"

SHELL=fish fish
